version: "3.3"

services:
  db:
    image: postgres
    container_name: invoice-scrapper-db
    environment:
      POSTGRES_SERVER: invoice_scrapper
      POSTGRES_DB: invoice_scrapper
      POSTGRES_USER: invoice_scrapper
      POSTGRES_PASSWORD: "invoice_scrapper" 
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - /home/matayoos/repos/data/invoice-scraper:/var/lib/postgresql/data
    networks:
      - invoice-scraper-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: invoice-scrapper-pgamin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: 'matayoos@protonmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'matayoosPgadmin'
    ports:
      - '8004:80'
    depends_on:
      - db
    networks:
      - invoice-scraper-network
  

networks:
  invoice-scraper-network:
    driver: bridge
